name: Create DUBBD Package
description: Creates a DUBBD Zarf package for the requested path

inputs:
  username:
    description: Registry1 user
    required: true
  password:
    description: Registry1 PW
    required: true
  working-dir:
    description: DUBBD zarf.yaml path
    required: true
  download-init-package: 
    description: Include Zarf init package?
    required: false

outputs:
  latest-package-version:
    description: The latest DUBBD package version
    value: ${{ steps.latest-package-version.outputs.latest-package-version }}

runs:
  using: composite
  steps:
    - name: Login to Registry1
      uses: docker/login-action@v2
      with:
        registry: registry1.dso.mil
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        
    - name: Create Zarf Package
      uses: ./.github/actions/create-zarf-package
      with:
        working-dir: ${{ inputs.working_dir }}
