name: Terraform Testing
description: Testing Terraform with Terratest

inputs:
  test_retry:
    description: 'Retry count'
    default: 1
    type: number
  test_timeout:
    description: Go test timeout as a string
    default: 30m
    type: string
  test_dir:
    description: Testing directory used as workflow working directory.
    default: ./test
    type: string

defaults:
  run:
    shell: bash -euo pipefail

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Go from go.mod
      uses: actions/setup-go@v4
      working-directory: ${{ inputs.test_dir }}
      with:
        go-version-file: ./${{ inputs.test_dir }}/go.mod

    - name: Install Go Dependencies
      shell: bash
      working-directory: ${{ inputs.test_dir }}
      run: go mod tidy

    - name: Test with terratest
      shell: bash
      working-directory: ${{ inputs.test_dir }}
      run: go test -count ${{ inputs.test_retry }} -timeout ${{ inputs.test_timeout }} -v .

