name: Terraform Formatting
Description: Apply Terraform formatting and commit changes to branch

inputs:
  github-token:
    description: GitHub token to authenticate to the GitHub REST API from the host repo
    required: true

# output:
#   formatted-tf:
#     description: Files Terraform fmt fixed
#     value: ${{ steps.tffmt.outputs.formatted }}
#   branch:
#     description: Current branch 
#     value: ${{ steps.getbranch.outputs.branch }}

runs:
  using: composite 
  steps:
    - name: Get branch
      shell: bash
      id: getbranch 
      run: echo "branch=$(git branch|grep \* |awk '{print $2}')" >> $GITHUB_OUTPUT
    
    - name: Echo Values
      shell: bash
      run: echo "Branch; ${{ steps.getbranch.outputs.branch }}"

      # Use the REST API to commit changes, so we get automatic commit signing
    - name: Commit changes
      shell: bash
      env:
        # GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        formatted=$(terraform fmt -recursive)
        for i in $formatted; do echo $i; done;
        for fixed in $formatted; do
          BRANCH="${{ steps.getbranch.outputs.branch }}"
          MESSAGE="chore: Terraform fmt of $fixed from common workflows"
          export SHA=$( git rev-parse $BRANCH:$fixed )
          export CONTENT=$( base64 -i $fixed )
          gh api --method PUT /repos/defenseunicorns/${{ github.repository }}/contents/$fixed \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$BRANCH" \
            --field sha="$SHA"
          sleep 1
        done;
