name: Terraform Formatting
Description: Apply Terraform formatting and commit changes to branch

inputs:
  github-token:
    description: GitHub token to authenticate to the GitHub REST API from the host repo
    required: true

output:
  formatted-tf:
    description: Files Terraform fmt fixed
    value: ${{ steps.tffmt.outputs.formatted }}
  branch:
    description: Current branch 
    value: ${{ steps.getbranch.outputs.branch }}

runs:
  using: composite 
  steps:
    - name: Run Terraform formatting
      shell: bash
      id: tffmt
      run: echo "formatted=$(terraform fmt -recursive)" >> $GITHUB_OUTPUT
    
    - name: Get branch
      shell: bash
      id: getbranch 
      run: echo "branch=$(git branch|grep \* |awk '{print $2}')" >> $GITHUB_OUTPUT
    
      # Use the REST API to commit changes, so we get automatic commit signing
    - name: Commit changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        for fixed in ${{ steps.tffmt.outputs.formatted }}; do
          export BRANCH="${{ steps.getbranch.outputs.branch }}"
          export MESSAGE="chore: Terraform fmt of $fixed from common workflows"
          export SHA=$( git rev-parse $BRANCH:$fixed )
          export CONTENT=$( base64 -i $fixed )
          gh api --method PUT /repos/defenseunicorns/${{ github.repository }}/contents/$fixed \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$BRANCH" \
            --field sha="$SHA"
        done;

    - name: Commit formatting changes 
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Fixed Terraform Formatting in GitHub action"
        git push