name: Create DUBBD Package
description: Creates a DUBBD Zarf package for the requested path

inputs:
  working-dir:
    description: Zarf package path
    required: true
  download-init-package: 
    description: Include Zarf init package
    required: false

outputs:
  latest-package-version:
    description: The latest DUBBD package version
    value: ${{ steps.latest-package-version.outputs.latest-package-version }}

runs:
  using: composite
  steps:        
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.27.1
        download-init-package: ${{ inputs.download-init-package }}

    - name: Create Zarf Package
      shell: bash
      run: zarf package create --confirm
      working-directory: ${{ inputs.working-dir }}
