name: Bump Zarf Package Version
on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: zarf-dummy
          extra-files: '/test1/zarf.yaml'