name: Bump Zarf Package Version
on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

jobs:
  version-zarf:
    runs-on: ubuntu-latest  
    env:
      working-directory: ${{inputs.working-dir}}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        version-file: zarf.yaml
        version-path: metadata.version