name: Bump Zarf Package Version
on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Tag
        uses: google-github-actions/release-please-action@v3
      # https://github.com/google-github-actions/release-please-action
        with:
          command: manifest # use configs in release-please-config.json
          release-type: simple

