name: Publish

# Will remove before merge and make it only tags
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  dummy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Triggered by tag creation"