name: Publish

# Will remove before merge and make it only tags
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        shell: bash
        run: |
          echo "Triggered by tag creation"
          echo "github.ref_type: ${{github.ref_type}}"
          echo "github.ref: ${{github.ref}}"
          echo "github.event: ${{github.event}}"
          echo "github.ref_name: ${{github.ref_name}}"