name: Publish

# Will remove before merge and make it only tags
on:
  create:

permissions:
  contents: read
  packages: write

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Triggered by tag creation ${{github.ref_type == 'tag'}} ${{github.ref_type}}"