name: Publish

# Will remove before merge and make it only tags
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Triggered by tag creation"