name: Publish

# Will remove before merge and make it only tags
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        shell: bash
        run: |
          echo "Triggered by tag creation ${{github.ref_type == 'tag'}} ${{github.ref_type}}"