name: Test Terraform with Terratest

on:
  workflow_call:
    inputs:
      test_retry:
        required: false
        description: 'Retry count'
        default: 3
        type: number

run-name: ${{ github.actor }} is testing Terraform in ${{ github.repository }}
jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Go Dependencies
        shell: bash
        run: go mod tidy

      - name: Test with terratest
        shell: bash
        run: go test -count ${{ inputs.test_retry }} -v ./...

