name: Test Workflows
on:
  push:
    branches:
      - main
jobs:
  version-zarf-package:
    name: Version Zarf Package
    uses: defenseunicorns/uds-common-workflows/.github/workflows/bump-zarf-package-version@main
    secrets: inherit
    with: 
      working-dir: ./test1
